config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  # Login stuff
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # Search
  get '/search', to: 'travel_packages#search'
  get '/searchresults', to: 'travel_packages#searchresults'
  
  # Purchasing
  get '/confirmation', to: 'travel_packages#confirmation'
  get '/agentpackages', to: 'travel_packages#searchbyagent'
  
  # Friends
  get '/follow', to: 'users#addfriend'
  get '/unfollow', to: 'users#removefriend'
  get '/following', to: 'friends#index'
  
  resources :users
  resources :messages
  resources :travel_packages
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    attr_accessor :remember_token # token for remembering users
    before_save { self.email = email.downcase }
    validates(:name, presence: true, length: {maximum: 50} )
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    has_many :travel_packages
    has_many :messages
    has_many :puchase_histories
    has_many :friends
    
    validates(
        :email, presence: true, length: {maximum: 255},
        format: { with: VALID_EMAIL_REGEX },
        uniqueness: { case_sensitive: false }
        )
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }, allow_blank: true

    # Gets a hash for a string
    def User.digest(string)
        cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
        BCrypt::Password.create(string, cost: cost)
    end
    
    # Random token
    def User.new_token
        SecureRandom.urlsafe_base64
    end
    
    # Remember user for longer sessions
    def remember
        self.remember_token = User.new_token
        update_attribute(:remember_digest, User.digest(remember_token))
    end
    
    # True if the token matches the digest
    def authenticated?(remember_token)
        return false if remember_digest.nil?
        BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end
    
    # Need to be able to forget users, too so we can logout
    def forget
        update_attribute(:remember_digest, nil)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: [:destroy]
  
  def index
    #@users = User.all # All users
    if (current_user.usertype == 2)
      @users = User.where('usertype != ?', 2)
    else
      @users = User.where('active = ? and private = ? and usertype != ?', true, false, 2) # get users
      # @users = User.all
    end
    @heading = "All users"
  end

  # show the user, will generate the appropriate buttons
  def show
    @user = User.find(params[:id])
    @purchases = PurchaseHistory.where("traveller_id = ?", @user)
    @friend = Friend.where("user = ? and friend = ?", current_user.id, @user.id).count
    @is_friend = false
    if @friend > 0
      @is_friend = true
    end
  end
  
  def new
    @user = User.new # doesn't do anything right now
  end
  
  def create
    @user = User.new(user_params)
    @user.active = true
    @user.private = false
    if @user.save
      # Handle a successful save
      log_in @user
      flash[:success] = "Welcome to WeLuv2Travel.net!"
      redirect_to user_url(@user)
    else
      render 'new'
    end
  end
  
  # Add a friend here.
  def addfriend
    @user = User.find(params[:friend])
    @friend_item = Friend.new( {
      confirmed: false,
      user: current_user.id,
      friend: @user.id,
      friend_name: @user.name,
      friend_email: @user.email
    })
  
    if @friend_item.save
      flash[:success] = "Following."
      redirect_to user_url(params[:friend])
    else
      flash[:danger] = "Sorry, that didn't save..."
      redirect_to root_url
    end
  end
  
  # Remove that friend
  def removefriend
    @friend_item = Friend.find_two_friends(current_user.id, params[:friend]).first
    
    @friend_item.destroy
    flash[:success] = "Unfollowed this user."
    redirect_to user_url(params[:friend])
  end
  
  def edit
  end
  
  def update
    if @user.update_attributes(user_params)
      # Success
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end

  # Doesn't actually destroy, just make inactive  
  def destroy
    # User.find(params[:id]).destroy
    # flash[:success] = "User deleted"
    # redirect_to users_url
    @user = User.find(params[:id])
    @user.active = false
    if (@user.save)
      flash[:success] = 'User successfully deactivated.'
    else
      flash[:danger] = 'Something went wrong.  Unable to delete.'
    end
    redirect_to users_url
  end
  
  private # --------------------------------------------------------------------
  
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :usertype, :active, :private)
    end
    
    # before filters
    # confirm logged-in user
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
    # confirm correct user
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless (current_user?(@user) || current_user.usertype == 2)
    end
    
    # confirms admin
    def admin_user
      redirect_to(root_url) unless current_user.usertype == 2
    end
end

app/helpers/users_helper.rb
module UsersHelper
    
    # Returns the Gravatar for the given user.
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
    
    def gravatar_for_friend(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.friend_email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.friend_name, class: "gravatar")
    end
end

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if (current_user.usertype == 2) && !current_user?(user) %> | 
    <%= link_to "edit", edit_user_path(user) %> | 
    <% if user.active? %>
      <%= link_to "deactivate", user, method: :delete, data: { confirm: "Are you sure you want to deactivate #{user.name}?" } %>
    <% else %>
      Deactivated    
    <% end %>
  <% end %>
</li>
<div class="fh5co-spacer fh5co-spacer-xxs"></div>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>

	<aside id="fh5co-hero" style="background-image: url(<%= asset_path("images/travel_airplane.jpg") %>);">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<div class="fh5co-hero-wrap">
						<div class="fh5co-hero-intro">
								<h2>User Profile<span></span></h2>
								<h1>Update Your Information</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
	</aside>
	
<div id="fh5co-main">

                <section>
					<div class="container">
						<div class="row">
							<div class="col-md-12">
								<h2 class="fh5co-uppercase-heading-sm text-center">Please Enter Account Info</h2>
								<div class="fh5co-spacer fh5co-spacer-sm"></div>
							</div>
							<div class="col-md-8 col-md-offset-2">
							<%= form_for(@user) do |f| %>
                    <%= render 'shared/error_messages' %>
                                
										<div class="col-md-6">
										<div class="form-group">
										<%= f.label :name, class: 'sr-only' %>
										<%= f.text_field :name, class: 'form-control input-lg', placeholder:'Your Name' %>
										</div>
										</div>
										
										<div class="col-md-6">
										<div class="form-group">
										<%= f.label :email, class: 'sr-only' %>
										<%= f.email_field :email, class: 'form-control input-lg', placeholder:'Email' %>
										</div>
										</div>
										
										<div class="col-md-12">
										<div class="form-group">
										<%= f.label :password, class: 'sr-only' %>
										<%= f.password_field :password, class: 'form-control input-lg', placeholder:'Password' %>
										</div>
										</div>
										
										<div class="col-md-12">
										<div class="form-group">
										<%= f.label :password_confirmation, "Confirm Password", class: 'sr-only' %>
										<%= f.password_field :password_confirmation, class: 'form-control input-lg', placeholder:'Confirm Password' %>
										</div>
										</div>
										
										<% if current_user.usertype == 2 %>
											<div class="col-md-6">
											<div class="form-group">
											<table><tbody><tr>										
											<td><%= f.label :usertype, "Create Packages" %></td>
											<td>&nbsp;</td>
											<td><%= f.check_box :usertype %></td>
											</tr></tbody></table>
											</div>
											</div>
											<div class="col-md-6">
											<div class="form-group">
											<table><tbody><tr>
											<td><%= f.label :active, "Active" %></td>
											<td>&nbsp;</td>
											<td><%= f.check_box :active %></td>
											</tr></tbody></table>
											</div>
											</div>
										<% end %>
										
										
										
										
										<div class="col-md-6">
										<div class="form-group">
										<%= f.submit "Save changes", class: "btn btn-primary" %>
										</div>
										</div>
										
										<div class="col-md-6">
										<div class="form-group">
										<table><tbody><tr>
							      	<td><%= f.label :private %></td>
							      	<td>&nbsp;</td>
    									<td><%= f.check_box :private %></td>
    								</tr></tbody></table>
    								</div>
    								</div>
                <% end %>
							</div>
						</div>

					</div>
				</section>
</div>

app/views/users/index.html.erb
<% provide(:title, @heading) %>

	<aside id="fh5co-hero" style="background-image: url(<%= asset_path("images/spinx_-_Roderick_Eime.jpg") %>);">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<div class="fh5co-hero-wrap">
						<div class="fh5co-hero-intro">
								<h2>Users<span></span></h2>
								<h1><%= @heading %></h1>
						</div>
					</div>
				</div>
			</div>
		</div>
	</aside>
	
<div id="fh5co-main">


					<section>
					<div class="container">
						<div class="row">
								<%= render 'shared/flash_messages' if !flash.empty? %>

							<div class="col-md-8">
	              <ul style="list-style-type: none">
	                <%= render @users %>
	              </ul>
							</div>

						</div>
					</div>
				</section>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign Up') %>

	<aside id="fh5co-hero" style="background-image: url(<%= asset_path("images/travel_airplane.jpg") %>);">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<div class="fh5co-hero-wrap">
						<div class="fh5co-hero-intro">
								<h2>New User<span></span></h2>
								<h1>Sign Up</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
	</aside>
	
<div id="fh5co-main">

                <section>
					<div class="container">
						<div class="row">
							<div class="col-md-12">
								<h2 class="fh5co-uppercase-heading-sm text-center">Please Enter Account Info</h2>
								<div class="fh5co-spacer fh5co-spacer-sm"></div>
							</div>
							<div class="col-md-8 col-md-offset-2">
								<%= form_for(@user, url: signup_path) do |f| %>
									<%= render 'shared/error_messages' %>
									
									<div class="col-md-6">
									<div class="form-group">
									<%= f.label :name, class: 'sr-only' %>
									<%= f.text_field :name, class: 'form-control input-lg', placeholder:'Your Name' %>
									</div>
									</div>
									
									<div class="col-md-6">
									<div class="form-group">
									<%= f.label :email, class: 'sr-only' %>
									<%= f.email_field :email, class: 'form-control input-lg', placeholder:'Email' %>
									</div>
									</div>
									
									<div class="col-md-12">
									<div class="form-group">
									<%= f.label :password, class: 'sr-only' %>
									<%= f.password_field :password, class: 'form-control input-lg', placeholder:'Password' %>
									</div>
									</div>
									
									<div class="col-md-12">
									<div class="form-group">
									<%= f.label :password_confirmation, "Confirm Password", class: 'sr-only' %>
									<%= f.password_field :password_confirmation, class: 'form-control input-lg', placeholder:'Confirm Password' %>
									</div>
									</div>
									
									<div class="col-md-6">
									<div class="form-group">
									<%= f.submit "Create my account", class: "btn btn-primary" %>
									</div>
									</div>
	              <% end %>
							</div>
						</div>

					</div>
				</section>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
	<aside id="fh5co-hero" style="background-image: url(<%= asset_path("images/travel_airplane.jpg") %> );">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<div class="fh5co-hero-wrap">
						<div class="fh5co-hero-intro">
								<h2>User Profile<span></span></h2>
								<h1><%= @user.name %></h1>
						</div>
					</div>
				</div>
			</div>
		</div>
	</aside>
	
<div id="fh5co-main">

		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2 text-center fh5co-lead-wrap">
					<h2 class="fh5co-serif fh5co-lead">
					    <%= gravatar_for @user, {size: 200} %><%= @user.name %>, <%= @user.email %>
          </h2>

					<% if current_user != @user %>
					<div class="row">
					    <%= link_to "Send Message", new_message_path(:recipient => @user.email), class:"btn btn-outline btn-lg"%>
					    
					    <% if @is_friend %>
					      <%= link_to 'Unfollow', unfollow_path(:friend => @user.id), class:"btn btn-outline btn-lg" %>
					    <% else %>
					      <%= link_to 'Follow', follow_path(:friend => @user.id), class:"btn btn-outline btn-lg" %>
					    <% end %>
					
					  <% if @user.usertype == 1 %>
					    <%= link_to "See all my packages", agentpackages_path(:agent => @user.id), class:"btn btn-outline btn-lg" %>
					  <% end %>
					</div>
					<% end %>          
          
				</div>
				
				<%= render 'shared/flash_messages' if !flash.empty? %>
				
			</div>
		</div>
		
		<% if @purchases.count > 0 %>
		<div class="container">
			<div class="row">

			    <h2>Travel History</h2>

			    <div class="table-responsive">
			    <table class="table table-condensed table-hover ">
			    <thead>
			      <tr>
			        <th>Name</th>
			        <th>Destination</th>
			      </tr>
			    </thead>
			    
			    <tbody>
			      <% @purchases.each do |p| %>
			        <tr>
			          <td><%= link_to p.name, travel_package_url(p.package_id) %></td>
			          <td><%= p.location %></td>
			        </tr>
			      <% end %>
			    </tbody>
			    </table>
			    </div>
			    
			</div>
		</div>
		<% end %>
		
</div>