config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  # Login stuff
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # Search
  get '/search', to: 'travel_packages#search'
  get '/searchresults', to: 'travel_packages#searchresults'
  
  # Purchasing
  get '/confirmation', to: 'travel_packages#confirmation'
  get '/agentpackages', to: 'travel_packages#searchbyagent'
  
  # Friends
  get '/follow', to: 'users#addfriend'
  get '/unfollow', to: 'users#removefriend'
  get '/following', to: 'friends#index'
  
  resources :users
  resources :messages
  resources :travel_packages
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/travel_package.rb
class TravelPackage < ApplicationRecord
  belongs_to :user
  validates :name, presence: true
  
  def TravelPackage.search(tag)
    skLIKE = "ILIKE" # PSQL style
    if Rails.env.development? # using SQLITE3 in development...
      skLIKE = "LIKE"
    end
    q = "%#{tag}%"
    where("(tags #{skLIKE} ? or name #{skLIKE} ? or location #{skLIKE} ? or airport #{skLIKE} ?) and active = ?", q, q, q, q, true)
  end
  
  def TravelPackage.allForID(theID)
    where(user_id: theID, active: true)
  end
end

app/controllers/travel_packages_controller.rb
class TravelPackagesController < ApplicationController
  before_action :set_travel_package, only: [:show, :edit, :update, :destroy]
  before_action :correct_user,   only: [:index, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]

  # GET /travel_packages
  # GET /travel_packages.json
  def index
    if current_user.usertype == 2
      @travel_packages = TravelPackage.where(active: true)
    else
      @travel_packages = TravelPackage.allForID(session[:user_id])
    end
  end

  # GET /travel_packages/1
  # GET /travel_packages/1.json
  def show
    @agent = User.find(@travel_package.user_id)
  end

  # GET /travel_packages/new
  def new
    @travel_package = TravelPackage.new
  end

  # GET /travel_packages/1/edit
  def edit
  end

  # POST /travel_packages
  # POST /travel_packages.json
  def create
    @travel_package = TravelPackage.new(travel_package_params)
    myID = session[:user_id]
    @travel_package.user_id = myID
    @travel_package.active = true

    if @travel_package.save
      flash[:success] = 'Travel package was successfully created.'
      redirect_to travel_packages_url(@travel_package)
    else
      render 'new'
    end
  end

  # PATCH/PUT /travel_packages/1
  # PATCH/PUT /travel_packages/1.json
  def update
    if @travel_package.update(travel_package_params)
      # Successful update
      flash[:success] = "Updated successfully."
      redirect_to @travel_package
    else # not successful :(
      render :edit
    end
  end


  # DELETE /travel_packages/1
  # DELETE /travel_packages/1.json
  # doesn't actually destroy the object, since the data is used for historical records
  def destroy
    # @travel_package.destroy
    # flash[:success] = "Package successfully deleted."
    @travel_package.active = false
    if @travel_package.save
      flash[:success] = 'Travel package was successfully deleted.'
    else
      flash[:danger] = 'Unable to delete.'
    end
    redirect_to travel_packages_url
  end

  def search
    
  end
  
  # Searches on multiply keywords
  def searchresults
    # @travel_packages = TravelPackage.search(params[:search])
    
    @keys = params[:search].split
    @travel_packages = TravelPackage.search(@keys.shift)
    
    @keys.each do |k|
      @r = TravelPackage.search(k)
      @travel_packages = @travel_packages.or(@r)
    end
  end
  
  def searchbyagent
    @travel_packages = TravelPackage.allForID(params[:agent])
    
    render :searchresults
  end

  def confirmation
    # This would need a more complex system, but since we have no actual purchase system
    #   it occurs here as a simple passthrough
    @travel_package = TravelPackage.find(params[:pack])
    @purch = PurchaseHistory.new({amount: @travel_package.price, 
                                  traveller_id: current_user.id, 
                                  agent_id: @travel_package.user_id, 
                                  package_id: @travel_package.id,
                                  location: @travel_package.location,
                                  name: @travel_package.name
    })
    if @purch.save
      @destination = @travel_package.location
      @confirmation = @purch.id
    else
      flash[:danger] = "Sorry, that didn't save..."
      redirect_to root_url
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_travel_package
      @travel_package = TravelPackage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def travel_package_params
      params.require(:travel_package).permit(:name, :price, :location, :description, 
                    :flight_num, :flight_depart, :flight_arrive, :tags,
                    :return_num, :return_depart, :return_arrive,
                    :airport, :returnairport
                    )
    end
    
    # before filters ------------------------
    # confirm logged-in user
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Please log in to view this page."
        redirect_to login_url
      end
    end
    
    # confirm correct user
    def correct_user
      if !logged_in? || current_user.usertype < 1
        flash[:warning] = "You cannot access this page"
        redirect_to root_url
      end
    end
end

app/helpers/travel_packages_helper.rb
module TravelPackagesHelper
end

app/views/travel_packages/_form.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">
  
<%= form_for(travel_package) do |f| %>
  <% if travel_package.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
        <%= pluralize(travel_package.errors.count, "error") %> prohibited this travel_package from being saved:</div>

      <ul>
      <% travel_package.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.number_field :price %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <table>
    <tbody>
      <tr>
        <td><%= f.label "Leaves from" %>
        <%= f.text_field :airport %></td>
        <td><%= f.label :flight_num %>
        <%= f.text_field :flight_num %></td>
        <td><%= f.label :flight_depart %>
        <%= f.text_field :flight_depart %></td>
        <td><%= f.label :flight_arrive %>
      <%= f.text_field :flight_arrive %></td>
      </tr>
    </tbody>
  </table>
  
  <table>
    <tbody>
      <tr>
        <td><%= f.label "Returns From" %>
        <%= f.text_field :returnairport %></td>
        <td><%= f.label :return_num %>
        <%= f.text_field :return_num %></td>
        <td><%= f.label :return_depart %>
        <%= f.text_field :return_depart %></td>
        <td><%= f.label :return_arrive %>
      <%= f.text_field :return_arrive %></td>
      </tr>
    </tbody>
  </table>
  
  <div class="field">
    <%= f.label :tags %>
    <%= f.text_field :tags %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-lg btn-primary", role: "button" %>
  </div>
<% end %>

</div>
</div>

app/views/travel_packages/confirmation.html.erb
<% provide(:title) %>

	<aside id="fh5co-hero" style="background-image: url(<%= asset_path("images/lanterns.jpg") %> );">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<div class="fh5co-hero-wrap">
						<div class="fh5co-hero-intro">
								
						</div>
					</div>
				</div>
			</div>
		</div>
	</aside>
	
	
<div id="fh5co-main">
  <div class="container">
  
    <div class="row">
    <div class="col-md-6 col-md-offset-3">
    <h1>Congratulations on your purchase!</h1>
    <p>We hope that you enjoy <%= @destination %>!</p>
    
    <p>Your agent will send contact you with further package details.</p>
    <h2>Your confirmation number is WL2T00<%= @confirmation %></h2>
    <p>This site does not process payments, but it would have been handled here.</p>
    </div>
    </div>
  
  </div>
</div>

app/views/travel_packages/edit.html.erb
<% provide(:title, 'Edit Package') %>

	<aside id="fh5co-hero" style="background-image: url(<%= asset_path("images/travel_airplane.jpg") %> );">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<div class="fh5co-hero-wrap">
						<div class="fh5co-hero-intro">
								<h2>Create a journey<span></span></h2>
								<h1>Edit Package</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
	</aside>


<div id="fh5co-main">

		<div class="container">
			<div class="row">

        <h1>Editing Travel Package</h1>
        
        <div class="row">
        <div class="col-md-6 col-md-offset-3">
          
        <%= link_to 'Show', @travel_package %> |
        <%= link_to 'Back', travel_packages_path %>
        
        </div></div>
        
        <%= render 'form', travel_package: @travel_package %>
</div>
</div>
</div>

app/views/travel_packages/index.html.erb
<% provide(:title, 'Packages') %>

	<aside id="fh5co-hero" style="background-image: url(<%= asset_path("images/holi.jpg") %> );">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<div class="fh5co-hero-wrap">
						<div class="fh5co-hero-intro">
								<h2>See the horizon<span></span></h2>
								<h1>Travel Packages</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
	</aside>

<div id="fh5co-main">

		<div class="container">
			<div class="col-md-12">
      <%= render 'shared/flash_messages' if !flash.empty? %>
      </div>
		  
			<div class="row">
        <% if current_user.usertype == 2 %>
          <h1>All Travel Packages</h1>
          
          <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th> - </th>
                <th>Name</th>
                <th>Destination</th>
                <th>Tags</th>
              </tr>
            </thead>
          
            <tbody>
              <% @travel_packages.each do |travel_package| %>
                <tr>
                  <td><%= link_to 'Edit', edit_travel_package_path(travel_package) %> / 
                    <%= link_to 'Delete', travel_package, method: :delete, data: 
                    { confirm: 'Are you sure you want to delete this package?' } %></td>
                  <td><%= link_to travel_package.name, travel_package %></td>
                  <td><%= travel_package.location %></td>
                  <td><%= travel_package.tags %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          </div>
          
        <% else %>
          <h1>Travel Packages</h1>
          
          <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th> - </th>
                <th>Name</th>
                <th>Price</th>
                <th>Destination</th>
                <th>Airport</th>
                <th>Flight number </th>
                <th>Flight departure</th>
                <th>Flight arrival</th>
                <th colspan="3"></th>
              </tr>
            </thead>
          
            <tbody>
              <% @travel_packages.each do |travel_package| %>
                <tr>
                  <td><%= link_to 'Edit', edit_travel_package_path(travel_package) %> / 
                    <%= link_to 'Delete', travel_package, method: :delete, data: 
                    { confirm: 'Are you sure you want to delete this package?' } %></td>
                  <td><%= link_to travel_package.name, travel_package %></td>
                    <td><%= number_to_currency(travel_package.price, precision: 0) %></td>
                  <td><%= travel_package.location %></td>
                  <td><%= travel_package.airport %></td>
                  <td><%= travel_package.flight_num %></td>
                  <td><%= travel_package.flight_depart %></td>
                  <td><%= travel_package.flight_arrive %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          </div>
          
          <%= link_to 'New Travel Package', new_travel_package_path, class: "btn btn-lg btn-primary", role: "button" %>
        <% end %>
</div>
</div>
</div>

app/views/travel_packages/new.html.erb
<% provide(:title, 'New Package') %>

	<aside id="fh5co-hero" style="background-image: url(<%= asset_path("images/fuji_00.jpg") %> );">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<div class="fh5co-hero-wrap">
						<div class="fh5co-hero-intro">
								<h2>Create a journey<span></span></h2>
								<h1>New Package</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
	</aside>


<div id="fh5co-main">

		<div class="container">
			<div class="row">
        <h1>New Travel Package</h1>
        
        <div class="row">
          <div class="col-md-6 col-md-offset-3">
            <%= link_to 'Back', travel_packages_path %>
          </div>
        </div>
        
        <%= render 'form', travel_package: @travel_package %>
        
      </div>
    </div>
</div>

app/views/travel_packages/search.html.erb
<% provide(:title, 'Search') %>

	<aside id="fh5co-hero" style="background-image: url(<%= asset_path("images/explore-8.jpg") %> );">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<div class="fh5co-hero-wrap">
						<div class="fh5co-hero-intro">
								<h2>Explore. Dream. Discover.<span></span></h2>
								<h1>Travel Packages</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
	</aside>
	
	
<div id="fh5co-main">
    
    
    
    <section>
    <div class="container">
    	<div class="row">

    		<div class="col-md-8 col-md-offset-2 text-center fh5co-lead-wrap">
    			<h2 class="fh5co-uppercase-heading-sm text-center">Please enter your search criteria</h2>

    		    <div class="col-md-8 col-md-offset-2">
    			    <%= form_tag(searchresults_path, :method => "get", id: "search-form") do %>
    					<div class="col-md-12">
    					<div class="form-group">
                        <%= text_field_tag("search", nil, class: "form_control input-lg", placeholder:"Enter search") %>
                        </div>
                        </div>
                        <div class="col-md-12">
    					<div class="form-group">
                        <%= submit_tag("Go", :name => nil, class: "btn btn-lg btn-primary", role: "button" ) %>
                        </div>
                        </div>
                    <% end %>
				</div>
						
					<div class="fh5co-spacer fh5co-spacer-sm"></div>
				</div>
    		
    		</div>
    
    	</div>
    	
    	<div class="fh5co-spacer fh5co-spacer-xxs"></div>
    </section>
</div>

app/views/travel_packages/searchresults.html.erb
<% provide(:title, 'Search') %>

	<aside id="fh5co-hero" style="background-image: url(<%= asset_path("images/fuji_00.jpg") %> );">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<div class="fh5co-hero-wrap">
						<div class="fh5co-hero-intro">
								<h2>Find a destination<span></span></h2>
								<h1>Travel Packages</h1>
						</div>
					</div>
				</div>
			</div>
		</div>
	</aside>


<div id="fh5co-main">
<% if @travel_packages.count > 0 %>
<section>
<div class="container">
<div class="row">
  <div class="table-responsive">
  <table class="table table-condensed table-hover ">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Destination</th>
        <th>Airport</th>
        <th>Flight number </th>
        <th>Flight departure</th>
        <th>Flight arrival</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @travel_packages.each do |travel_package| %>
        <tr>
          <td><%= link_to travel_package.name, travel_package %></td>
          <!--<td><%= travel_package.price %></td>-->
          <td><%= number_to_currency(travel_package.price, precision: 0) %></td>
          <td><%= travel_package.location %></td>
          <td><%= travel_package.airport %></td>
          <td><%= travel_package.flight_num %></td>
          <td><%= travel_package.flight_depart %></td>
          <td><%= travel_package.flight_arrive %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  </div>
</div>
</div>
</section>
<% else %>
<section>
<div class="container">
<div class="row">
  <h2>Sorry, there were no results that matched your search.</h2>
</div></div></section>
<% end %>

    <section>
    <div class="container">
    	<div class="row">

    		<div class="col-md-8 col-md-offset-2 text-center fh5co-lead-wrap">
    			<h2 class="fh5co-uppercase-heading-sm text-center">Please enter new search criteria</h2>

    		    <div class="col-md-8 col-md-offset-2">
    			    <%= form_tag(searchresults_path, :method => "get", id: "search-form") do %>
    					<div class="col-md-12">
    					<div class="form-group">
                        <%= text_field_tag("search", nil, class: "form_control input-lg", placeholder:"Enter search") %>
                        </div>
                        </div>
                        <div class="col-md-12">
    					<div class="form-group">
                        <%= submit_tag("Go", :name => nil, class: "btn btn-lg btn-primary", role: "button" ) %>
                        </div>
                        </div>
                    <% end %>
				</div>
						
					<div class="fh5co-spacer fh5co-spacer-sm"></div>
				</div>
    		
    		</div>
    
    	</div>
    	
    	<div class="fh5co-spacer fh5co-spacer-xxs"></div>
    </section>
    
</div>    

app/views/travel_packages/show.html.erb
<% provide(:title, 'Package Detail') %>
	<aside id="fh5co-hero" style="background-image: url(<%= asset_path("images/sanfran.jpg") %> );">
		<div class="container">
			<div class="row">
				<div class="col-md-8 col-md-offset-2">
					<div class="fh5co-hero-wrap">
						<div class="fh5co-hero-intro">
								<h2>Package Detail<span></span></h2>
								<h1><%= @travel_package.name %></h1>
						</div>
					</div>
				</div>
			</div>
		</div>
	</aside>
	
<div id="fh5co-main">	
  <section>
  <div class="container">
  <div class="row">
      <div class="col-md-12">
  			<h2 class="fh5co-uppercase-heading-sm text-center">Offered by <%= @agent.name %></h2>
  			
  			<div id="fh5co-tab-feature-center" class="fh5co-tab text-center">
  				<ul class="resp-tabs-list hor_1">
  					<li><i class="fh5co-tab-menu-icon ti-world"></i>Trip Detail</li>
  					<li><i class="fh5co-tab-menu-icon ti-arrow-top-right"></i> Flight</li>
  					<li><i class="fh5co-tab-menu-icon ti-back-left"></i> Return</li>
  				</ul>
  				<div class="resp-tabs-container hor_1">
  					<div>
  						<div class="row">
  							<div class="col-md-12">
  								<h2 class="h3">Package: <%= @travel_package.name %></h2>
  							</div>
  							<div class="col-md-6">
  								<p>Price: $<%= @travel_package.price %></p>
  								<p>Location: <%= @travel_package.location %></p>
  							</div>
  							<div class="col-md-6">
  								<p><%= @travel_package.description %></p>
  							</div>
  						</div>
  					</div>
  					
  					<div>
  						<div class="row">
  							<div class="col-md-12">
  								<h2 class="h3">Flight Information</h2>
  							</div>
  							<div class="col-md-6">
  								<p>Airport: <%= @travel_package.airport %></p>
  								<p>Flight: <%= @travel_package.flight_num %></p>
  							</div>
  							<div class="col-md-6">
  								<p>Departure: <%= @travel_package.flight_depart %></p>
  								<p>Arrival: <%= @travel_package.flight_arrive %></p>
  							</div>
  						</div>
  					</div>
  					
  					<div>
  						<div class="row">
  							<div class="col-md-12">
  								<h2 class="h3">Returning Flight</h2>
  							</div>
  							<div class="col-md-6">
  								<p>Airport: <%= @travel_package.returnairport %></p>
  								<p>Flight: <%= @travel_package.return_num %></p>
  							</div>
  							<div class="col-md-6">
  								<p>Departure: <%= @travel_package.return_depart %></p>
  								<p>Arrival: <%= @travel_package.return_arrive %></p>
  							</div>
  						</div>
  					</div>
  				</div>
  			</div>
  		</div>
  </div>
  </div>
  </section>

  <section>
  <div class="container">
  <div class="row">
    <div class="col-md-12">
    <% if current_user.id == @travel_package.user_id &&current_user.usertype != 0  && @travel_package.active %>
      <%= link_to 'Edit', edit_travel_package_path(@travel_package), class: "btn btn-lg btn-primary", role: "button" %>
      <%= link_to 'Back', travel_packages_path, class: "btn btn-lg btn-primary", role: "button" %>
    <% else %>
      <div class="col-lg-6">
      <%= link_to "Contact this Travel Agent", user_path(@travel_package.user_id), class:"btn btn-lg btn-primary", role:"button" %>
      </div>
      <% if @travel_package.active %>
        <div class="col-lg-6">
        <%= link_to "Buy this package", confirmation_url(:do => :confirm, :pack => @travel_package), class:"btn btn-lg btn-primary", role:"button" %>
        </div>
      <% else %>
        <div class="col-lg-6">
          This package is not for sale.
        </div>
      <% end %>
    <% end %>
    </div>
  </div>
  </div>
  </section>
</div>