config/routes.rb
Rails.application.routes.draw do

  get 'sessions/new'

  get 'users/new'

  root 'static_pages#home'
  
  get '/help', to: 'static_pages#help'
  get '/about', to: 'static_pages#about'
  get '/contact', to: 'static_pages#contact'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  
  # Login stuff
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # Search
  get '/search', to: 'travel_packages#search'
  get '/searchresults', to: 'travel_packages#searchresults'
  
  # Purchasing
  get '/confirmation', to: 'travel_packages#confirmation'
  get '/agentpackages', to: 'travel_packages#searchbyagent'
  
  # Friends
  get '/follow', to: 'users#addfriend'
  get '/unfollow', to: 'users#removefriend'
  get '/following', to: 'friends#index'
  
  resources :users
  resources :messages
  resources :travel_packages
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_footer.html.erb
				<footer id="fh5co-footer">
					<div class="container">

						<p class="text-muted fh5co-no-margin-bottom text-center">
							<small>&copy; May 2017 <%= link_to "Contact", contact_path %> This project is brought to you by Team Cupcake in COSC 612. 
							<a href="http://www.towson.edu/">Towson University</a></small></p>

					</div>
				</footer>

app/views/layouts/_header.html.erb
<!-- START #fh5co-header -->
			<header id="fh5co-header-section" role="header" class="" >
				<div class="container">
					
					<!-- START #fh5co-logo, has Site Title-->
					<h1 id="fh5co-logo" class="pull-left"><%= link_to "WeLuv2Travel", root_path, id: "logo" %></h1>
					
					<!-- START #fh5co-menu-wrap -->
					<nav id="fh5co-menu-wrap" role="navigation">
						<ul class="sf-menu" id="fh5co-primary-menu">
							<li><%= link_to "About", about_path %></li>

            <% if logged_in? %>
              <li><%= link_to "Search", search_url %></li>
              <li><%= link_to "Users", users_path %></li>
              <% if current_user.usertype == 2 %>
                <li><%= link_to "Packages", travel_packages_path %></li>
              <% end %>

              <% if (get_friends.count > 0) %>
                <li>
                  <a href="#" class="fh5co-sub-ddown">Following</a>
                  <ul class="fh5co-sub-menu">
                      <% get_friends.each do |u| %>
                        <li>
                          <%= link_to u.friend_name, user_path(u.friend) %>
                        </li>
                        <% end %>
                  </ul>
                </li>   
              <% end %>								
              <li>
									<a href="#" class="fh5co-sub-ddown">Account</a>
									 <ul class="fh5co-sub-menu">
		                <li><%= link_to "Home", home_link %></li>

	 	                <% if message_count == 0 %>
                      <li><%= link_to "Messages", messages_path %></li>
                    <% else %>
                      <li><%= link_to "Messages (#{message_count})", messages_path %></li>
                    <% end %>
									 	<li><%= link_to "My Profile", current_user %></li>
									 	<li><%= link_to "Update Profile", edit_user_path(current_user) %></li>
										<li><%= link_to "Log out", logout_path, method: "delete" %></li> 
									</ul>
								</li>
        	    <% else %>
              	<li><%= link_to "Log in", login_path, class: "btn btn-outline" %></li>
            	<% end %>
          </ul>
        </nav>
      </div>
    </header>

app/views/layouts/_rails_default.html.erb
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_shim.html.erb
    <!-- [if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= render 'layouts/rails_default' %>

  	<meta charset="utf-8">
	  <meta http-equiv="X-UA-Compatible" content="IE=edge">

	  <meta name="viewport" content="width=device-width, initial-scale=1">
	  <meta name="description" content="Towson U Software Engineering project" />
  	<meta name="keywords" content="towson project stevek.ninja" />
  	<meta name="author" content="Steven Dean Kennedy, Theme by FREEHTML5.CO" />
  	
  	<!-- Google Webfont -->
  	<link href='http://fonts.googleapis.com/css?family=Lato:300,400|Crimson+Text' rel='stylesheet' type='text/css'>
  	<!-- Themify Icons -->
  	<%= stylesheet_link_tag "themify-icons.css" %>
  	<!-- Bootstrap -->
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">  	<%= stylesheet_link_tag "owl.carousel.min.css" %>
  	<%= stylesheet_link_tag "owl.theme.default.min.css" %>
  	<!-- Magnific Popup -->
  	<%= stylesheet_link_tag "magnific-popup.css" %>
  	<!-- Superfish -->
  	<%= stylesheet_link_tag "superfish.css" %>
  	<!-- Easy Responsive Tabs -->
  	<%= stylesheet_link_tag "easy-responsive-tabs.css" %>
  
  	<!-- Theme Style -->
  	<%= stylesheet_link_tag "style" %>
  	
  	<!-- FOR IE9 below -->
  	<!--[if lt IE 9]>
  	<script src="js/modernizr-2.6.2.min.js"></script>
  	<script src="js/respond.min.js"></script>
	  <![endif]-->
  </head>

  <body>
    <%= render 'layouts/header' %>


    <%= yield %>
  
    
    <%= render 'layouts/footer' %>

		<!-- jQuery -->
		<%= javascript_include_tag "jquery-1.10.2.min.js" %>
		<!-- jQuery Easing -->
		<%= javascript_include_tag "jquery.easing.1.3.js" %>
		<!-- Bootstrap -->
		<%= javascript_include_tag "bootstrap.js" %>
		<!-- Owl carousel -->
		<%= javascript_include_tag "owl.carousel.min.js" %>
		<!-- Magnific Popup -->
		<%= javascript_include_tag "jquery.magnific-popup.min.js" %>
		<!-- Superfish -->
		<%= javascript_include_tag "hoverIntent.js" %>
		<%= javascript_include_tag "superfish.js" %>
		<!-- Easy Responsive Tabs -->
		<%= javascript_include_tag "easyResponsiveTabs.js" %>
		<!-- FastClick for Mobile/Tablets -->
		<%= javascript_include_tag "fastclick.js" %>
		<!-- Main JS -->
		<%= javascript_include_tag "main.js" %>
		
		
  </body>
</html>